server:
  port: 8000

spring:
 application:
  name: microservice-provider-user
 jpa:
   generate-ddl: false
   show-sql: true
   hibernate:
    ddl-auto: none
 datasource:
   platform: h2
   schema: classpath:schema.sql
   data: classpath:data.sql
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

info:
  app:
   name: microservice-provider-user
   encoding: UTF-8
  java:
   source: 1.8.0_131
   target: 1.8.0_131
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
    instance:
      prefer-ip-address: false

---
spring:
  profiles: provider1
server:
  port: 8000

---
spring:
  profiles: provider2
server:
  port: 8001
